### ISSUE TITLE
No robots.txt gets generated

### ISSUE THREAD

**Issue by triwats** [nuotsu/sanitypress#24]
Howdy, just wanted to check this wasn't something I misunderstood. Happy to have a go at this but noticed that there's a `!noIndex` option in the blog post - so not sure how you intend this to work.

Right now, there's a sitemap being generated (🙌), **but out of the box there is no `robots.txt` (404):**

```
20:59:30 ❯ curl -s -o /dev/null -w "%{http_code}" -L  "localhost:3002/robots.txt"
404⏎
```

**Comment by nuotsu** [comment]
Howdy!

1. Pages and blog posts where `metadata.noIndex == true` are not included in the sitemap generation ([sitemap.ts](https://github.com/nuotsu/sanitypress/blob/main/src/app/(frontend)/sitemap.ts#L19))
2. Instead of a robots.txt (not included in SanityPress out of the box), pages and blog posts will have the noindex `<meta>` tag added via the [`processMetadata()`](https://github.com/nuotsu/sanitypress/blob/main/src/lib/processMetadata.ts#L24-L26) function used in the route files.

There wasn't a need for a robot.txt out of the box. I just preferred users to add this as needed.
